# start: Ithan
import pyautogui
import time

def on_the_map_go_to(Name, type, input_left = 0, input_top = 250, input_width = 654, input_height = 1153):
	if type == 'npc':
		img_type = 'npc_on_map.png'
	elif type == 'doors':
		img_type = 'doors_on_map.png'

	podreczna_mapa_img = pyautogui.locateOnScreen('img\\Podreczna_mapa.png', region=(0, 250, 654, 524-250), confidence=0.8)
	left, top = podreczna_mapa_img[0], podreczna_mapa_img[1]
	pyautogui.click(left, top + 660)
	pyautogui.move(0, 100)
	pyautogui.hotkey('ctrl', 'a')
	pyautogui.press('delete')
	pyautogui.write(Name)

	object_on_map_img = pyautogui.locateOnScreen(f'img\\{img_type}', region=(input_left, input_top, input_width, input_height), confidence=0.98)
	pyautogui.click(object_on_map_img)
	pyautogui.click(21, 1241)

	time.sleep(0.5)
	while True:
		coordinates_1st_img = pyautogui.screenshot(region=(2006, 310, 2102-2006, 350-310))
		time.sleep(0.5)
		coordinates_2nd_img = pyautogui.screenshot(region=(2006, 310, 2102-2006, 350-310))
		time.sleep(0.5)
		coordinates_3rd_img = pyautogui.screenshot(region=(2006, 310, 2102-2006, 350-310))

		if coordinates_1st_img == coordinates_2nd_img == coordinates_3rd_img:
			time.sleep(0.5)
			break

def type_of_interaction(key):
	pyautogui.press(key)
	time.sleep(0.5)

def dialog_go_through(num, reps):
	for i in range(1, reps + 1):
		pyautogui.press(num)
		time.sleep(0.5)

def buy_from_shop(item_img_name, count):
	object_to_buy = pyautogui.locateOnScreen(f'img\\{item_img_name}', region=(1269, 502, 2548 - 1269, 1832 - 502), confidence=0.9)
	for i in range(1, count + 1):
		pyautogui.click(object_to_buy)
		time.sleep(0.1)
	accept_img = pyautogui.locateOnScreen(f'img\\shop_accept.png', region=(1269, 502, 2548 - 1269, 1832 - 502), confidence=0.9)
	pyautogui.click(accept_img)

def move_hero_one_tile_using_wsad(key):
	pyautogui.keyDown(key)
	time.sleep(0.1)
	pyautogui.keyUp(key)

on_the_map_go_to('Garus Tyrrak', 'npc')
type_of_interaction('r')
dialog_go_through('3', 1)
dialog_go_through('1', 9)

on_the_map_go_to('Zakon Planu Astralnego', 'npc')
type_of_interaction('r')
dialog_go_through('1', 1)
dialog_go_through('5', 1)
time.sleep(0.8)
on_the_map_go_to('Fort Eder', 'doors')
time.sleep(0.5)
on_the_map_go_to('Mokrad', 'doors')
on_the_map_go_to('Pod Zielonym Jednoro', 'doors')
on_the_map_go_to('p.1', 'doors')
on_the_map_go_to('Drimuarius', 'npc')
type_of_interaction('r')
dialog_go_through('1', 2)
dialog_go_through('2', 1)
dialog_go_through('1', 7)
time.sleep(2)
type_of_interaction('r')
dialog_go_through('1', 8)

on_the_map_go_to('Pod Zielonym Jednoro', 'doors')
on_the_map_go_to('Mokrad', 'doors')
on_the_map_go_to('Fort Eder', 'doors')
on_the_map_go_to('Eder', 'doors')
on_the_map_go_to('Zakon Planu Astralnego', 'npc')
type_of_interaction('r')
dialog_go_through('1', 1)
dialog_go_through('4', 1)
time.sleep(0.5)
on_the_map_go_to('Ratusz Karka-Han', 'doors')
on_the_map_go_to('Przybytek Zakonu Bia', 'doors')
on_the_map_go_to('Van Saur', 'npc')
type_of_interaction('r')
dialog_go_through('3', 1)
dialog_go_through('1', 3)
dialog_go_through('2', 1)
dialog_go_through('1', 5)

on_the_map_go_to('Ratusz Karka-Han', 'doors')
on_the_map_go_to('Karka-Han', 'doors', 274, 994)

on_the_map_go_to('Zakon Planu Astralnego', 'npc')
type_of_interaction('r')
dialog_go_through('1', 2)

on_the_map_go_to('Porzucone Pasieki', 'doors')
on_the_map_go_to('Wioska Pszczelarzy', 'doors')
on_the_map_go_to('Dom Jofusa', 'doors')
on_the_map_go_to('Dom Jofusa - Piwnica', 'doors')
on_the_map_go_to('Zakurzone przej', 'doors')
on_the_map_go_to('Radosna Polana', 'doors')
on_the_map_go_to('Kocham K.', 'npc')
type_of_interaction('r')
dialog_go_through('1', 2)
on_the_map_go_to('Casiopeia', 'npc')
type_of_interaction('r')
dialog_go_through('2', 2)
dialog_go_through('1', 1)
on_the_map_go_to('boka woda', 'npc')
type_of_interaction('r')
dialog_go_through('2', 1)
dialog_go_through('1', 1)
dialog_go_through('2', 1)
dialog_go_through('1', 1)

on_the_map_go_to('Zakurzone przej', 'doors')
on_the_map_go_to('Dom Jofusa - Piwnica', 'doors')
on_the_map_go_to('Dom Jofusa', 'doors')
on_the_map_go_to('Wioska Pszczelarzy', 'doors')
on_the_map_go_to('Porzucone Pasieki', 'doors')
on_the_map_go_to('Ithan', 'doors')
time.sleep(0.5)
on_the_map_go_to('Zakon Planu Astralnego', 'npc')
type_of_interaction('r')
dialog_go_through('1', 1)
dialog_go_through('4', 1)
on_the_map_go_to('Dom Menarik', 'doors')
time.sleep(0.5)
pyautogui.press('enter')
move_hero_one_tile_using_wsad('d')
type_of_interaction('r')
dialog_go_through('2', 1)
dialog_go_through('1', 1)
dialog_go_through('2', 1)
dialog_go_through('1', 2)
dialog_go_through('2', 1)
dialog_go_through('1', 1)

on_the_map_go_to('Ratusz Karka-Han', 'doors')
on_the_map_go_to('Przybytek Zakonu Bia', 'doors')
on_the_map_go_to('Van Saur', 'npc')
type_of_interaction('r')
dialog_go_through('3', 1)
dialog_go_through('1', 8)

on_the_map_go_to('Ratusz Karka-Han', 'doors')
on_the_map_go_to('Karka-Han', 'doors', 274, 994)
on_the_map_go_to('nik loch', 'npc')
time.sleep(0.5)
pyautogui.press('enter')
move_hero_one_tile_using_wsad('s')
type_of_interaction('r')
dialog_go_through('2', 1)
dialog_go_through('1', 2)
dialog_go_through('9', 1)
dialog_go_through('2', 1)
dialog_go_through('1', 1)
on_the_map_go_to('p.1', 'doors')
on_the_map_go_to('Aldar', 'npc')
type_of_interaction('r')
dialog_go_through('1', 5)
on_the_map_go_to('Lochy miejskie', 'doors')
on_the_map_go_to('Karka-Han', 'doors')
on_the_map_go_to('Dom Menarik', 'doors')
on_the_map_go_to('Potw', 'npc')
type_of_interaction('r')
dialog_go_through('1', 1)
dialog_go_through('2', 2)
dialog_go_through('1', 2)
dialog_go_through('2', 1)
dialog_go_through('1', 5)
dialog_go_through('2', 1)
dialog_go_through('1', 2)

on_the_map_go_to('Zegar', 'npc')
type_of_interaction('r')
dialog_go_through('2', 1)
dialog_go_through('1', 2)
dialog_go_through('2', 2)
dialog_go_through('1', 4)

on_the_map_go_to('Piecyk', 'npc')
type_of_interaction('r')
dialog_go_through('1', 1)
dialog_go_through('2', 1)
dialog_go_through('1', 1)

on_the_map_go_to('Karka-Han', 'doors')
on_the_map_go_to('Ratusz Karka-Han', 'doors')
on_the_map_go_to('nik skarbca', 'npc')
type_of_interaction('r')
dialog_go_through('1', 3)
time.sleep(0.5)
type_of_interaction('r')
dialog_go_through('2', 1)
dialog_go_through('3', 1)
dialog_go_through('1', 9)
dialog_go_through('2', 1)
on_the_map_go_to('Skrzynka', 'npc')
type_of_interaction('r')
dialog_go_through('1', 2)

on_the_map_go_to('Karka-Han', 'doors', 274, 994)
on_the_map_go_to('Dom Menarik', 'doors')
on_the_map_go_to('Piecyk', 'npc')
type_of_interaction('r')
dialog_go_through('2', 1)
dialog_go_through('1', 2)
dialog_go_through('2', 1)
dialog_go_through('1', 2)
move_hero_one_tile_using_wsad('d')
type_of_interaction('r')
dialog_go_through('2', 2)
dialog_go_through('1', 1)

on_the_map_go_to('Jama', 'npc')
type_of_interaction('r')
dialog_go_through('1', 4)
time.sleep(0.5)
on_the_map_go_to('cie z jaskini', 'npc')
type_of_interaction('r')
dialog_go_through('1', 1)
time.sleep(0.5)
on_the_map_go_to('ony dom', 'npc')
type_of_interaction('r')
on_the_map_go_to('Dalia', 'npc')
type_of_interaction('r')
dialog_go_through('1', 5)
dialog_go_through('2', 1)
dialog_go_through('1', 1)
on_the_map_go_to('Guvern', 'npc')
type_of_interaction('r')
dialog_go_through('1', 1)
on_the_map_go_to('Drimuarius', 'npc')
type_of_interaction('r')
dialog_go_through('1', 8)
dialog_go_through('2', 1)
dialog_go_through('1', 4)
dialog_go_through('2', 1)
time.sleep(0.5)

on_the_map_go_to('Terraco', 'npc')
type_of_interaction('r')
dialog_go_through('1', 3)
dialog_go_through('4', 2)
dialog_go_through('1', 8)

on_the_map_go_to('ony dom', 'npc')
type_of_interaction('r')
time.sleep(0.5)
on_the_map_go_to('Guvern', 'npc')
type_of_interaction('r')
on_the_map_go_to('Drimuarius', 'npc')
type_of_interaction('r')
dialog_go_through('1', 1)
time.sleep(0.5)
on_the_map_go_to('Terraco', 'npc')
type_of_interaction('r')
dialog_go_through('3', 1)
dialog_go_through('1', 14)
on_the_map_go_to('ony dom', 'npc')
type_of_interaction('r')
on_the_map_go_to('Drimuarius', 'npc')
type_of_interaction('r')
dialog_go_through('1', 2)

on_the_map_go_to('Garus Tyrrak', 'npc')
type_of_interaction('r')
dialog_go_through('1', 3)

on_the_map_go_to('Van Saur', 'npc')
type_of_interaction('r')
dialog_go_through('1', 7)

on_the_map_go_to('Hilanger', 'npc')
type_of_interaction('r')
dialog_go_through('1', 4)

on_the_map_go_to('Van Saur', 'npc')
type_of_interaction('r')
dialog_go_through('1', 3)



